server:
  port: 7070
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Shilpa_23
    url: jdbc:mysql://localhost:3306/miniproject
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
